# Generated by Django 3.1.5 on 2021-01-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.step'),
        ),
    ]
