# Generated by Django 3.1.5 on 2021-01-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210106_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='steps',
            field=models.ManyToManyField(related_name='script', to='bot.Step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.step'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=24)),
                ('answers', models.ManyToManyField(to='bot.Answer')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.script')),
            ],
        ),
    ]
